sonata_admin:
    title: 'Arcade Digital Signage'
    title_logo: build/images/arcade.png
    dashboard:
        blocks:
#            - { type: sonata.admin.block.admin_list, position: right }
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to Arcade Digital Signage</h2>
                        <p>This is a prototype and therefore everything is not fully working or easy to do.</p>
                        <p>Feel free to report problem on <a href="https://github.com/Rolel/arcade-digital-signage">GitHub</a>.</p>
            -
                class:    col-lg-4 col-xs-4
                position: top
                type:     sonata.admin.block.stats
                settings: { code: admin.screen, text: Screens, icon: fa-tv, color: bg-warning }
            -
                class:    col-lg-4 col-xs-4
                position: top
                type:     sonata.admin.block.stats
                settings: { code: admin.deck, text: Decks, icon: fa-stack-overflow , color: bg-info }
            -
                class:    col-lg-4 col-xs-4
                position: top
                type:     sonata.admin.block.stats
                settings: { code: admin.slide, text: Slides, icon: fa-square, color: bg-info }
            -
                class:    col-lg-6 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings: { code: admin.scoreboard, text: Score Board, icon: fa-list-ol, color: bg-teal }
            -
                class:    col-lg-6 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings: { code: admin.score, text: Score, icon: fa-star, color: bg-green }


sonata_block:
    blocks:
        sonata.block.service.text:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.stats:
            contexts: [admin]

sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~
